### ISSUE TITLE
Factor out the collision sequence generation

### ISSUE THREAD

**Issue by matthiasrichter** [ALICENorwayGroup/tpc-fee-sim#2]
Add functionality for deterministic generation of timeframes. By now, the sequence of collisions is generated randomly for every run. This does not allow deterministic studies with the same timeframe data.

tasks:
- Define a format to store generated collision sequence together with events and input raw files.
- Add option to DataGenerator to write the collision sequence in addition to timeframe generation.
- Add option to read and use such a configuration file instead of generating new sequence.

**Comment by KlewinS** [comment]
Would it not be easier to create a function which propagates a seed down to the CollisionDistribution class to start the random number generator with a defined, constant seed instead of the system time?
